# Generated by Django 2.2.7 on 2020-05-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sehri_iftar_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('sehri_hour', models.IntegerField()),
                ('sehri_minute', models.IntegerField()),
                ('iftar_hour', models.IntegerField()),
                ('iftar_minute', models.IntegerField()),
            ],
        ),
    ]
