# Generated by Django 2.2.7 on 2020-05-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramadan_time', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sehri_iftar_time',
            name='iftar_hour',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='sehri_iftar_time',
            name='sehri_hour',
            field=models.IntegerField(default=3),
        ),
    ]
